import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar/Navbar";

import "./globals.css";
import { allLessons } from "contentlayer/generated";
import { Search } from "@/types/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Linux Guide",
  description: "Generated by create next app",
};

const getSearchData = (): Search[] => {
  return allLessons.map((lesson) => {
    return {
      title: lesson.title,
      url: lesson.url_path,
      pathSegaments: lesson.pathSegments,
    };
  });
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const searchData = getSearchData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar searchData={searchData} />
        {children}
      </body>
    </html>
  );
}
