import { Inter, Fira_Code } from "next/font/google";

import Navbar from "@/components/Navbar/Navbar";

import { Search } from "@/types/Search";
import { allLessons } from "contentlayer/generated";

import "../../styles/globals.css";
import "../../styles/prose.css";
import "../../styles/highlight.css";

export const metadata = {
  title: "Linux Guide",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const fira_code = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
  display: "swap",
});

const getSearchData = (): Search[] => {
  return allLessons.map((lesson) => {
    return {
      title: lesson.title,
      url: lesson.url_path,
      pathSegaments: lesson.pathSegments,
    };
  });
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const searchData = getSearchData();
  return (
    <html lang="en" className={`${inter.variable} ${fira_code.variable}`}>
      <body>
        <Navbar searchData={searchData} />
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
