import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar/Navbar";

import "./globals.css";
import { allLessons } from "contentlayer/generated";
import { Search } from "@/types/Search";
import { PathSegment } from "@/types/PathSegment";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Linux Guide",
  description: "Generated by create next app",
};

const getSearchData = (): Search[] => {
  return allLessons
    .map((lesson) => {
      return {
        title: lesson.title,
        url: lesson.url_path,
        pathSegaments: lesson.pathSegments,
      };
    })
    .sort((first, second) => {
      const firstPaths: PathSegment[] = first.pathSegaments;
      const secondPaths: PathSegment[] = second.pathSegaments;

      for (
        let i = 0;
        i < Math.min(firstPaths.length, secondPaths.length);
        i++
      ) {
        if (firstPaths[i].pathName < secondPaths[i].pathName) {
          return -1;
        }
        if (firstPaths[i].pathName > secondPaths[i].pathName) {
          return 1;
        }
      }

      return 0;
    });
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const searchData = getSearchData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar searchData={searchData} />
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
